[package]
name = "pvxs"
version = "0.1.0"
edition = "2021"
description = "PVXS Rust library"
# license = ""
# repository = ""

[dependencies]
# For dynamic loading of shared libraries (e.g., pvxs.dll)
libloading = "0.8.6"

[dev-dependencies]
# For testing
assert_matches = "1.5.0"  # Optional: for ergonomic test assertions
